import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Navbar from "./Navbar";
import Footer from "./Footer";


function Layout( {children}:any ) {
  return (
     <>
      <Head>
        <title>Lease Holder - Rent Whatether Suits Your Soul.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box maxWidth="1280px" m="auto">
         <header>
            <Navbar/>
         </header>
         <main>
            {children}
         </main>
         <footer>
            <Footer/>
         </footer>
      </Box>
     </>
  );
}

export default Layout;

